steps:
- name: 'node:12'
  entrypoint: npm
  args: ['ci']
- name: 'node:12'
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-R', 'public', 'gs://staging.nodejs.dev/']
