steps:
- name: 'node:10'
  entrypoint: npm
  args: ['ci']
- name: 'node:10'
  entrypoint: npm
  args: ['run', 'build-ci']
  env:
    - 'PATH_PREFIX=staging.nodejs.dev/$SHORT_SHA'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-R', 'public', 'gs://staging.nodejs.dev/$SHORT_SHA']
