// This file is used to define all the changed slugs from original nodejs.org site to our new site.
// Note.: Gatsby requires trailing slashes on the path names
module.exports = {
  // Redirects old About pages path to the new ones
  '/governance/': '/en/about/governance/',
  '/working-groups/':
    'https://github.com/nodejs/TSC/blob/main/WORKING_GROUPS.md',
  '/releases/': '/en/about/releases/',
  '/privacy/': '/en/',
  '/en/about/privacy/': '/en/',
  '/security/': '/en/about/security/',
  // Outside Redirects
  '/trademark/': 'https://trademark-policy.openjsf.org/',
  '/about/trademark/': 'https://trademark-policy.openjsf.org/',
  '/en/about/trademark/': 'https://trademark-policy.openjsf.org/',
  // Redirects the old `/docs` path to `/api`
  '/docs/*': '/api/',
  '/storybook/*': '/en/',
  '/en/learn/the-package-json-guide/':
    'https://docs.npmjs.com/cli/v8/configuring-npm/package-json',
  '/the-package-json-guide/':
    'https://docs.npmjs.com/cli/v8/configuring-npm/package-json',
  '/en/learn/the-package-lockjson-file/':
    'https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json',
  '/en/learn/how-to-exit-from-a-nodejs-program/': '/en/learn/',
  '/en/learn/where-does-npm-install-the-packages/': '/en/learn/',
  '/en/learn/get-http-request-body-data-using-nodejs/': '/en/learn/',
  '/en/learn/a-brief-history-of-nodejs/': '/en/learn/',
  '/en/learn/nodejs-file-paths/': '/en/learn/',
  '/learn/asynchronous-work/blocking-vs-non-blocking':
    'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing',
  '/learn/discover-javascript-timers':
    'https://developer.mozilla.org/en-US/docs/Web/API/setTimeout',
  '/learn/modern-asynchronous-javascript-with-async-and-await':
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises',
  '/learn/the-nodejs-event-loop':
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises',
  '/blog/': '/en/blog',
  '/blog/advisory-board/2014/12/05/listening-to-the-community': '/en/blog',
  '/blog/community/2015/05/15/foundation-benefits-all/': '/en/blog',
  '/blog/community/2016/09/06/v5-to-v7': '/en/blog',
  '/blog/npm/2011/03/24/npm-1-0-global-vs-local-installation': '/en/blog',
  '/blog/vulnerabilities/2017/01/27/openssl-january-2017': '/en/blog',
  '/blog/vulnerabilities/2017/09/29/september-2017-path-validation': '/en/blog',
  '/blog/weekly-updates/2015/04/24/weekly-update.2015-04-24': '/en/blog',
  '/blog/weekly-updates/2015/05/29/weekly-update.2015-05-29': '/en/blog',
  '/blog/weekly-updates/2015/07/31/weekly-update.2015-07-31': '/en/blog',
  '/blog/weekly-updates/2016/02/15/weekly-update.2016-02-15': '/en/blog',
  '/blog/weekly-updates/2016/03/07/weekly-update.2016-03-07': '/en/blog',
  '/blog/weekly-updates/2016/08/15/weekly-update.2016-08-15': '/en/blog',
  '/en/blog/announcements/2021/10/07/retiring-the-node-js-community-committee':
    '/en/blog',
  '/en/blog/announcements/2022/02/14/nodejs-trademarks-transferred-to-openjs-foundation':
    '/en/blog',
  '/en/blog/announcements/2022/04/19/v18-release-announce': '/en/blog',
  '/en/blog/announcements/2022/06/08/nodejs16-eol': '/en/blog',
  '/en/blog/community/2016/12/03/update-v8-5.4': '/en/blog',
  '/en/blog/vulnerabilities/2018/06/12/june-2018-security-releases': '/en/blog',
  '/en/blog/weekly-updates/2015/07/17/weekly-update.2015-07-17': '/en/blog',
  '/en/blog/weekly-updates/2016/04/29/weekly-update.2016-04-29': '/en/blog',
  '/en/blog/weekly-updates/2016/07/22/weekly-update.2016-07-22': '/en/blog',
  '/en/blog/weekly-updates/2016/08/15/weekly-update.2016-08-15': '/en/blog',
  '/en/learn/accept-input-from-the-command-line-in-nodejs/': '/en/learn/',
  '/en/learn/asynchronous-flow-control/': '/en/learn/',
  '/en/learn/build-an-http-server/': '/en/learn/',
  '/en/learn/discover-javascript-timers/': '/en/learn/',
  '/en/learn/ecmascript-2015-es6-and-beyond/': '/en/learn/',
  '/en/learn/expose-functionality-from-a-nodejs-file-using-exports/':
    '/en/learn/',
  '/en/learn/find-the-installed-version-of-an-npm-package/': '/en/learn/',
  '/en/learn/how-to-log-an-object-in-nodejs/': '/en/learn/',
  '/en/learn/how-to-read-environment-variables-from-nodejs/': '/en/learn/',
  '/en/learn/how-to-use-the-nodejs-repl/': '/en/learn/',
  '/en/learn/install-an-older-version-of-an-npm-package/': '/en/learn/',
  '/en/learn/making-http-requests-with-nodejs/': '/en/learn/',
  '/en/learn/modern-asynchronous-javascript-with-async-and-await/':
    '/en/learn/',
  '/en/learn/nodejs-accept-arguments-from-the-command-line/': '/en/learn/',
  '/en/learn/nodejs-buffers/': '/en/learn/',
  '/en/learn/nodejs-streams/': '/en/learn/',
  '/en/learn/nodejs-with-typescript/': '/en/learn/',
  '/en/learn/nodejs-with-webassembly/': '/en/learn/',
  '/en/learn/output-to-the-command-line-using-nodejs/': '/en/learn/',
  '/en/learn/overview-of-blocking-vs-non-blocking/': '/en/learn/',
  '/en/learn/reading-files-with-nodejs/': '/en/learn/',
  '/en/learn/run-nodejs-scripts-from-the-command-line/': '/en/learn/',
  '/en/learn/semantic-versioning-using-npm/': '/en/learn/',
  '/en/learn/the-nodejs-event-loop/': '/en/learn/',
  '/en/learn/the-nodejs-events-module/': '/en/learn/',
  '/en/learn/the-npx-nodejs-package-runner/': '/en/learn/',
  '/en/learn/the-v8-javascript-engine/': '/en/learn/',
  '/en/learn/understanding-javascript-promises/': '/en/learn/',
  '/en/learn/understanding-setimmediate/': '/en/learn/',
  '/en/learn/uninstalling-npm-packages/': '/en/learn/',
  '/en/learn/update-all-the-nodejs-dependencies-to-their-latest-version/':
    '/en/learn/',
  '/en/learn/working-with-folders-in-nodejs': '/en/learn/',
  '/fr/learn/a-brief-history-of-nodejs/': '/fr/learn',
  '/fr/learn/build-an-http-server/': '/fr/learn',
  '/fr/learn/ecmascript-2015-es6-and-beyond/': '/fr/learn',
  '/fr/learn/error-handling-in-nodejs/': '/fr/learn',
  '/fr/learn/find-the-installed-version-of-an-npm-package/': '/fr/learn',
  '/fr/learn/javascript-asynchronous-programming-and-callbacks/': '/fr/learn',
  '/fr/learn/making-http-requests-with-nodejs/': '/fr/learn',
  '/fr/learn/nodejs-buffers/': '/fr/learn',
  '/fr/learn/nodejs-file-paths/': '/fr/learn',
  '/fr/learn/npm-dependencies-and-devdependencies/': '/fr/learn',
  '/fr/learn/run-nodejs-scripts-from-the-command-line/': '/fr/learn',
  '/fr/learn/the-nodejs-event-emitter/': '/fr/learn',
  '/fr/learn/the-nodejs-events-module/': '/fr/learn',
  '/fr/learn/the-nodejs-path-module/': '/fr/learn',
  '/fr/learn/update-all-the-nodejs-dependencies-to-their-latest-version/':
    '/fr/learn',
  '/fr/learn/working-with-folders-in-nodejs/': '/fr/learn',
  '/fr/learn/writing-files-with-nodejs/': '/fr/learn',
  '/learn/introduction-to-nodejs/': '/en/learn/',
  '/learn/the-nodejs-http-module/': '/en/learn/',
};
