name: 🔡 Internationalization and translations For Nodejs Website
description: Hello. Hola. Salut. Ciao. Здравствуйте. こんにちは.
labels: [i18n]
body:
  - type: markdown
    attributes:
      value: |
        Please mention the relevant localization team in your issue,
        it helps us having the right people take a look, or if you want
        to create a new localization team.
  - type: textarea
    attributes:
      label: 'Enter your issue on localizations here:'
      placeholder: |
        1. The name of the team (e.g: nodejs/node-cn).
        2. Any problems to report or you want to create it?
    validations:
      required: true
