on: check_suite
name: Post Staging Link on pull_request
jobs:
  postStagingLink:
    name: Post Staging Link
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Post Staging Link
      uses: ./.github/action/result-poster
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
